name: Docker Image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

  release:
    types: [released]

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build --build-arg ZSDK_TOOL=toolchain-arm . --file Dockerfile
          fi

  # Push image to GitHub Packages and Docker Hub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push ARM only to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          build_args: ZSDK_TOOL=toolchain-arm
          repository: zmkfirmware/zephyr-west-action-arm
          tag_with_ref: true
      - name: Push ARM only to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          build_args: ZSDK_TOOL=toolchain-arm
          repository: ${{ github.repository }}/zephyr-west-action-arm
          tag_with_ref: true
      - name: Push full SDK to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: zmkfirmware/zephyr-west-action
          tag_with_ref: true
      - name: Push full SDK to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/zephyr-west-action
          tag_with_ref: true
